### PR TITLE
Explicitly allow dynamic properties.

### LINKED ISSUE #174: Additional `cs:info` properties throw warning on PHP 8.2
# Please follow the general troubleshooting steps first:

- [ ] I read the README and followed the instructions.
- [ ] I am sure that the used CSL metadata follows the [CSL schema](https://github.com/citation-style-language/schema/blob/master/csl-data.json).
- [ ] I use a valid CSL stylesheet

### Bug reports:

Warnings emitted under PHP 8.2 due to other CSL 1.0.1 properties.

#### Used CSL stylesheet: ####

http://www.zotero.org/styles/chicago-fullnote-bibliography

`chicago-fullnote-bibliography.csl`

#### Used CSL metadata ####

Please replace these lines with your used metadata, for instance:

Not relevant for the issue, any will do.

---

The warnings in particular:

```
Deprecated function: Creation of dynamic property Seboettg\CiteProc\Root\Info::$category is deprecated in Seboettg\CiteProc\Root\Info->__construct() (line 62 of /var/www/html/vendor/seboettg/citeproc-php/src/Root/Info.php). 
Deprecated function: Creation of dynamic property Seboettg\CiteProc\Root\Info::$summary is deprecated in Seboettg\CiteProc\Root\Info->__construct() (line 62 of /var/www/html/vendor/seboettg/citeproc-php/src/Root/Info.php). 
Deprecated function: Creation of dynamic property Seboettg\CiteProc\Root\Info::$updated is deprecated in Seboettg\CiteProc\Root\Info->__construct() (line 62 of /var/www/html/vendor/seboettg/citeproc-php/src/Root/Info.php). 
Deprecated function: Creation of dynamic property Seboettg\CiteProc\Root\Info::$rights is deprecated in Seboettg\CiteProc\Root\Info->__construct() (line 62 of /var/www/html/vendor/seboettg/citeproc-php/src/Root/Info.php). 
```

It appears that `chicago-fullnote-bibliography` defines `cs:info/cs:category` elements as per [the 1.0.1 spec](https://docs.citationstyles.org/en/v1.0.1/specification.html#info), which throws this warning.

In the warnings, it's flagging:
- `category`
- `summary`
- `updated` and
- `rights`

However, it appears that this could pop for other allowed properties, such as:
- `title-short`
- `issn`/`eissn`/`issnl`
- `published`

Naively, these could probably be stashed in something like:

```diff
diff --git a/src/Root/Info.php b/src/Root/Info.php
index 50a4666..2656c99 100644
--- a/src/Root/Info.php
+++ b/src/Root/Info.php
@@ -34,6 +34,8 @@ class Info
      */
     private $links;

+    private $misc = [];
+
     public function __construct(SimpleXMLElement $node)
     {
         $this->authors = [];
@@ -95,4 +97,13 @@ class Info
     {
         return $this->links;
     }
+
+    public function __get(string $name) {
+      return $this->misc[$name] ?? NULL;
+    }
+
+    public function __set(string $name, $value) : void {
+      $this->misc[$name][] = $value;
+    }
+
 }
```

### PR DESCRIPTION
**Pull request by adam-vessey**
Fixes #174

### CODE REVIEW

**Review by kesah — APPROVED** [review]
Its' work in PHP 8.2.

File: src/Root/Info.php [hunk 1]
```diff
@@ -95,4 +97,13 @@ public function getLinks()
...
         return $this->links;
     }
+
+    public function __get(string $name) {
+      return $this->misc[$name] ?? NULL;
+    }
+
+    public function __set(string $name, $value) : void {
+      $this->misc[$name][] = $value;
+    }
```
Comment (trackleft) [inline src/Root/Info.php:107]:
```suggestion
    public function __get(string $name) 
    {
      return $this->misc[$name] ?? NULL;
    }

    public function __set(string $name, $value) : void 
    {
      $this->misc[$name][] = $value;
    }
```
